import "./globals.css";
import type { Metadata } from "next";
import { Inter, Kanit } from "next/font/google";

const kanit = Kanit({
  preload: true,
  style: "normal",
  display: "swap",
  subsets: ["latin"],
  variable: "--font-kanit",
  weight: ["400", "500", "700"],
});
const inter = Inter({
  preload: true,
  style: "normal",
  display: "swap",
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <meta name="theme-color" content="rgb(9 9 11)" />
        <meta name="google-adsense-account" content="ca-pub-5836460971552859" />
      </head>
      <body
        className={`${kanit.variable} ${inter.variable} antialiased font-inter text-gray-50 bg-zinc-950`}
      >
        {children}
      </body>
    </html>
  );
}
